# Default initial positions for ur10e_hande_robot's ros2_control fake system

initial_positions:
  elbow_joint: 0
  hande_left_finger_joint: 0
  hande_right_finger_joint: 0
  shoulder_lift_joint: 0
  shoulder_pan_joint: 0
  wrist_1_joint: 0
  wrist_2_joint: 0
  wrist_3_joint: 0