# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - group_ur_controller
    - group_gr_controller

  group_ur_controller:
    type: FollowJointTrajectory
    joints:
      - ur_shoulder_pan_joint
      - ur_shoulder_lift_joint
      - ur_elbow_joint
      - ur_wrist_1_joint
      - ur_wrist_2_joint
      - ur_wrist_3_joint
  group_gr_controller:
    type: GripperCommand
    joints:
      - gr_hande_left_finger_joint
    action_ns: gripper_cmd
    default: true