planning_plugin: ompl_interface/OMPLPlanner

manipulator:
  default_planner_config: RRTConnect
  planner_configs:
    - RRTConnect
    - RRT
  projection_evaluator: joints(shoulder_pan_joint,shoulder_lift_joint)
  longest_valid_segment_fraction: 0.005

hande_gripper:
  default_planner_config: RRTConnect
  planner_configs:
    - RRTConnect
  longest_valid_segment_fraction: 0.1

planner_configs:
  RRTConnect:
    type: geometric::RRTConnect
    range: 0.0
  RRT:
    type: geometric::RRT
    range: 0.0
    goal_bias: 0.05