# 기본 플래너를 OMPL로 설정
default_planning_pipeline: ompl

planning_pipelines: 
  - ompl
  - chomp
  - pilz_industrial_motion_planner

# OMPL 파이프라인 설정
ompl:
  planning_plugin: ompl_interface/OMPLPlanner
  planning_config_loader: "moveit_ros_planning/DynamicReconfigureLoader"
  default_planner_config: RRTConnectkConfigDefault
  request_adapters: >-
    default_planner_request_adapters/AddTimeOptimalParameterization
    default_planner_request_adapters/FixWorkspaceBounds
    default_planner_request_adapters/FixStartStateBounds
    default_planner_request_adapters/FixStartStateCollision
    default_planner_request_adapters/FixStartStatePathConstraints

# CHOMP 파이프라인 설정  
chomp:
  planning_plugin: chomp_interface/CHOMPPlanner
  request_adapters: ""

# Pilz 파이프라인 설정
pilz_industrial_motion_planner:
  planning_plugin: pilz_industrial_motion_planner/CommandPlanner
  request_adapters: ""