# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # 컨트롤러들
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    scaled_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    hande_gripper_controller:
      type: position_controllers/GripperActionController

# Joint State Broadcaster (핵심: 모든 조인트 상태 병합)
joint_state_broadcaster:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint  
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
      - robotiq_hande_left_finger_joint
    


# UR10e 조인트 컨트롤러
scaled_joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: false

# Hande 그리퍼 컨트롤러
hande_gripper_controller:
  ros__parameters:
    joint: robotiq_hande_left_finger_joint